### ISSUE TITLE
Http post request for commenting videos

### ISSUE THREAD

**Issue by penolegrus** [user234683/youtube-local#12]
Hello there! I just found your project on Github and I have some questions, could you please answer it? :)
I just trying to make a software which will use browser cookies and leave comments under youtube videos and I cant figure out how to do it using http requests. So I founded your project and I cant authorize youtube accounts.
Please if you have free time, could you add me in skype and help me with making post requests for adding comments on youtube videos?
I want to comment videos using Node JS or Http requests using browser cookies without official youtube api

**Comment by user234683** [comment]
Sorry, I don't have time to provide individual help for unrelated things. The comment-posting feature in youtube-local is broken right now and is going to be removed soon because posting comments without the in-page tracking and javascript of Youtube results in the comments being shadowbanned and your account de-trusted so that even comments within Youtube are shadowbanned. If you want to find out how to post comments, use the browser devtools to inspect the network requests on Youtube. The youtube-dl project has code that demonstrates the process for logging into Youtube accounts.
