### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by GurharinderSingh** [user234683/youtube-local#120]
Thank You

**Comment by user234683** [comment]
LibreWolf version and OS? Have you tested it in another browser? It's possible librewolf might have disabled access to local network servers. Also, this probably isn't the problem, but make sure you're keeping the server open when you try to connect.

To answer the questions, youtube-local should use less CPU and RAM than YouTube's webpage (for instance, it's common to hear laptops fans spinning when having a lot of YouTube tabs open). You can increase privacy by enabling Tor routing. If you want to go a step further, you can also enable Tor video routing.

**Comment by GurharinderSingh** [comment]
He

> LibreWolf version and OS? Have you tested it in another browser? It's possible librewolf might have disabled access to local network servers. Also, this probably isn't the problem, but make sure you're keeping the server open when you try to connect.
> 
> To answer the questions, youtube-local should use less CPU and RAM than YouTube's webpage (for instance, it's common to hear laptops fans spinning when having a lot of YouTube tabs open). You can increase privacy by enabling Tor routing. If you want to go a step further, you can also enable Tor video routing.

Thank You kind sir, i found the error today, it was something specific to my pc hence deleted the issue, basically my laptop was killing the command prompt(like if it was functionally turned off) and hence it could never find the server, Thanks a lot between, i found it even faster than loading standard youtube (probably due to dropping most of javascript (and this speed is not due to adds being removed, as i already had add blocker and tracking prevention), it genuinely made stuff faster

**Comment by user234683** [comment]
> I have a small request though, is there anyway to run videos i lower quality, selecting lower quality from the options just makes the video not play, but as soon as i increase quality to 360, it works great

This might be because LibreWolf doesn't support proprietary codecs (such as H.264 and AAC). In the settings page for youtube-local, change VP8/VP9 Codec Ranking to be `#1`, AV1 Codec Ranking to be `#2`, and H.264 Codec Ranking to be `#3`. Also, JavaScript is required for qualities other than 360p and 720p.

If that doesn't work, right click the page, click 'Inspect element', then click 'Console', then copy and paste the console output here.

> And i have yet another request, is there a way that you can implement (i don't know its complexity) to only get audio of a video, that is, the data of video graphics is never downloaded and just audio being downloaded, as it will be great to get either an option in low data, or for listening podcasts

Yes, issue #44 deals with this request. Unfortunately I'm pressed for time and won't be able to work on the issue for a long time. However, in the mean time, you can use the Downloads dropdown and click on an "audio only" source to listen to that and even save the audio-only file.

**Comment by GurharinderSingh** [comment]
Yes i got the quality work around, no i will try to get h264 to work, between thanks again sir
