### ISSUE TITLE
Refreshing of Subscription feed

### ISSUE THREAD

**Issue by GurharinderSingh** [user234683/youtube-local#122]
Small issues, is there a way to quickly check if a channel has uploaded and if so, be it updated in the subscription feed, the reason being, the cmd prompt running bat file slowly checks each channel if they have uploaded a video, as sometimes it has been really wonky, like a video which was uploaded 40 or so hours ago was now made available in feed, i know it is not easy, but something like how in newpipe, if we hard reload, all channels are checked, and within 20-30 seconds, it refreshes the feed, i am open to running code in cmd prompt if necessary
And please make so that pressing spacebar while playing the video doesn't scroll down the page and only pause it, because i am just way too much used to pausing video by spacebar

**Comment by user234683** [comment]
You can click the check buttons on individual channels or click the
check all button to check all channels. After clicking those buttons,
the command prompt will print out which channels are being checked and
when it's done you can refresh the page to see the new videos.

The reason it checks channels slowly by default is to cut down on the
number of requests, since it is common for people to have hundreds of
subscriptions. It checks channels at 10x the avergae rate which the
channel uploads videos. So, for example, if a channel uploads once
every 10 weeks, it will only check the channel once a week, which means
it could potentially be up to week until a new video is noticed.

If you have a group of channels (e.g. 20 chanenls) you want to check
immediately, but don't want to wait for all the others (e.g. 200
others) to be checked, you can assign them to a tag, and the
subscription page will allow you to check all channels associated with
that tag only.

**Comment by user234683** [comment]
Also if you want to play/pause the video, you can press k. I recommend
opening a separate issue for the spacebar hotkey. I don't have time to
implement it at the moment but zrose might be interested in it
