### ISSUE TITLE
Does it even make sense to route searches through tor but not videos?

### ISSUE THREAD

**Issue by ohnonot** [user234683/youtube-local#138]
This is really more of a discussion than an issue.

Routing everything through tor would be unbearably slow in most cases, and not nice for the tor network/community as a whole. Apart from that my question is not about low bandwidth and speed, it's about anonymity.

I imagine that youtube easily recognizes the connection if I make a search via tor and then immediately watch a video that comes up in that search.
In that scenario I believe using tor is actually doing more harm than good, because I'm more or less exposing my IP as being "one of those pesky privacy freaks"?

My opinion is not made up on that topic, I invite discussion and technical detail. Prove me wrong, maybe.

**Comment by user234683** [comment]
Cannot give a proper reply at the moment, just a couple notes:
- "Except video" means that only the video file itself is not routed. The rest of the requests for the video page and metadata etc. are routed through Tor. It is considered unlikely that YouTube would internally use video file requests for recommendations and other tracking, since they can always rely on the video page requests normally. They very likely log the video file IP for debugging purposes, however.
- I suggest checking out this issue with a before-and-after test: https://github.com/user234683/youtube-local/issues/123 Though this does not prove that the IP logging for video files is not fed into recommendations for that IP address. Would need to try a test where you had Tor routing, watched certain types of videos, then turned it off and checked if those certain type of videos were recommended to your usual IP address.

**Comment by user234683** [comment]
Some additional comments

> Routing everything through tor would be unbearably slow in most cases

Yes

> and not nice for the tor network/community as a whole. 

See https://github.com/user234683/youtube-local/issues/7 for a discussion about the cost of routing video through tor. The actual cost on the Tor network due to routing videos is quite small, there's an estimate in the readme seciton on tor video routing.

If your threat model is just avoiding commercial data mining by YouTube and you're concerned about not routing videos through Tor, using youtube-local via a VPN instead is a good option. Because of HTTPS, all the VPN sees is that you're connecting to youtube.com (not sensitive), and YouTube doesn't know who you are. This argument doesn't quite apply for general web browsing via a VPN generally since the domain names themselves can be sensitive, but that's a different debate.

> I don't really like to use YT as such at all - and this repo is a significant step towards that - so I won't be comparing recommendations in a with/without test.

The test is pretty easy and you don't have to use youtube really. You just watch certain types of videos in youtube-local for awhile with Tor routing on that you would expect to trigger recommendations. Then you visit youtube.com (while not logged into your youtube account) at the conclusion of the experiment. If it's true that youtube looks at googlevideo.com (video file) requests and uses that for recommendations, you would expect to see recommendations based on what you watched in youtube-local.

This test wouldn't tell you whether they log video file requests and use it for other purposes or hand it over to the NSA
