### ISSUE TITLE
Channel profile pictures doesn't load.

### ISSUE THREAD

**Issue by VictorXPDE** [user234683/youtube-local#163]
![image](https://user-images.githubusercontent.com/60672615/215930981-0810f00f-8f0a-40ba-a243-9e1cb534b907.png)

Opening the profile picture in a new tab gives me the Error 404
![image](https://user-images.githubusercontent.com/60672615/215931652-2e7c4580-8f38-4715-9704-ca55af39b028.png)

**Comment by zrose584** [comment]
Can confirm, the URL is wrong: ` http://youtube.local/https://www.youtube.com/channel/UCBa659QWEk1AI4Tg--mrJ2A/None` - It happens when using one of the sort options `Sort by oldest` or `Sort by views`, When using the default `Sorted by newest` it is correct

**Comment by SergeantAcoustic** [comment]
> Can confirm, the URL is wrong: ` http://youtube.local/https://www.youtube.com/channel/UCBa659QWEk1AI4Tg--mrJ2A/None` - It happens when using one of the sort options `Sort by oldest` or `Sort by views`, When using the default `Sorted by newest` it is correct

I believe this is a separate issue, in this case the avatar is missing but the channel isn't none. The issue seems to be that youtube-local fails to fetch data from `yt3.googleusercontent.com` links. I "fixed" it on my end by removing the start of these links and prepending `https://yt3.ggpht.com`, the URL used for avatars on comments.
