### ISSUE TITLE
Video player option Plyr probably has an old version (2017?) not supporting full screen by double-click or?

### ISSUE THREAD

**Issue by khlsvr** [user234683/youtube-local#167]
The video player option Plyr doesn't go to full screen mode when double-clicking on the video. I searched the Plyr github repo about this and it seems they have implemented this feature around December 2017 - https://github.com/sampotts/plyr/pull/740

If the reason for double-clicking not going to full screen mode in youtube-local's Plyr is because of the 2017 or older version of Plyr, what's the right way to update the youtube-local's Plyr version? I can see the following files having "plyr" in the path or filename:

/opt/youtube-local/youtube/static/plyr_fixes.css
/opt/youtube-local/youtube/static/js/plyr-start.js
/opt/youtube-local/youtube/static/modules/plyr
/opt/youtube-local/youtube/static/modules/plyr/blank.webm
/opt/youtube-local/youtube/static/modules/plyr/build-instructions.md
/opt/youtube-local/youtube/static/modules/plyr/plyr.css
/opt/youtube-local/youtube/static/modules/plyr/plyr.js
/opt/youtube-local/youtube/static/modules/plyr/plyr.svg

On the other hand there are way more files in the Plyr's github repo. For example a src/js directory already contains so many files https://github.com/sampotts/plyr/tree/master/src/js that I'm not sure if I can just copy those files youtube-local is using and expect it to work, right?

**Comment by user234683** [comment]
I disabled double-click to full screen because I found it annoying when
trying to pause and unpause a video to catch a certain point and it
would activate fullscreen.

You can press the "f" hotkey to go fullscreen. Alternatively, in

youtube-local/youtube/static/js/plyr-start.js

you can remove these lines, 126 - 132:

// disable double click to fullscreen
// https://github.com/sampotts/plyr/issues/1370#issuecomment-528966795
player.eventListeners.forEach(function(eventListener) {
    if(eventListener.type === 'dblclick') {
        eventListener.element.removeEventListener(eventListener.type,
eventListener.callback, eventListener.options);
    }
});
