### ISSUE TITLE
When in theater mode, video height exceeds screen viewport

### ISSUE THREAD

**Issue by Yogotami** [user234683/youtube-local#171]
As title says and using Firefox (latest release), video is bigger than my screen size.
![image](https://github.com/user234683/youtube-local/assets/87908747/7a8e97df-f959-491b-bbf8-692633b5c6c2)

Changing the value of height in #video-container-inner from `height: 100%` to `height: calc(100vh - 50px)` seems to resolve the problem.
![image](https://github.com/user234683/youtube-local/assets/87908747/2f73b49b-a951-4b38-ab23-ba92faa84e36)
 
![image](https://github.com/user234683/youtube-local/assets/87908747/a57e2fb2-0045-4780-b6fa-ec79e56f9ac0)

This 50px comes from trial and error but does not resolve the entire problem as it creates another:
![image](https://github.com/user234683/youtube-local/assets/87908747/77c8f508-0c5f-4e68-b133-8a0ab8ad12b4)

As I'm not as savvy as a lot of you guys, I have no idea how to decisively fix this.

**Comment by molytov** [comment]
I found a sort of band-aid solution.
In `youtube-local/youtube/templates/watch.html`, go to Line 90.
Change the % from 100% to a smaller value. I found 60% works for 1080p videos, but this differs depending on resolution.

`padding-top: calc(100%*var(--video_height)/var(--video_width));`
Change to
`padding-top: calc(60%*var(--video_height)/var(--video_width));`

Restart the service to ensure changes take effect.

This actually kind of exposes another issue, which is the fact that the video player size changes with the resolution setting.
This solution only works as long as you don't change resolutions. If you lower resolution to something like 360p, then your player will be much smaller.
The [yt-local fork on SourceHut](https://git.sr.ht/~heckyel/yt-local) seems to not have this issue, so it might help to see how it handles the player dimensions.

**Comment by user234683** [comment]
> This actually kind of exposes another issue, which is the fact that the video player size changes with the resolution setting.

This is intentional. If the video player size is too large for the height of the video, then the video will be blurry (e.g. you wouldn't want to go fullscreen on a 240p video). Whereas if it is too small, then most of the resolution of the video is being ignored (you _would_ want to watch a 1080p/4k video on fullscreen)

So the displayed height of the video in pixels needs to be equal to height of the video's resolution (360 pixels high for 360p). But if the video resolution is too big, the width needs to not exceed the browser width. So you need to scale the video down, while keeping the aspect ratio, which CSS is really bad at unless you have the required width available in pixels (because it won't accept percentages in the calculations).

To make things really fun, CSS does not provide the width of the browser window. It provides the width of the window plus the width scrollbar in the form of 100vw, which is pretty useless for this purpose (or any purpose really) since we can't exceed the scrollbar and do not know what width it is.

If that was it, maybe this would be tractable, but there's other things as well:
- For long (e.g. 3 hour) videos, if the resolution is say 360p, it will be difficult to scrub in the video, because 1 pixel might correspond to 3 minutes. So you have to sit there and wait 3 minutes to get to the desired part, after painstakingly trying to move your mouse a single pixel. The solution to this is to widen the scrub-bar to be the entire width of the screen if necessary.
- Both plyr and non-plyr (browser default) need to be supported. Plyr puts the `<video>` inside a bunch of `<div>`s, whereas the browser default does not. So both cases need to be handled.

Unfortunately, CSS is not well designed for trying to accomplish this, or really anything at all. I've had a tower of ducttape and ugly hacks that makes this work, but the browser vendors keep changing/breaking stuff :\

![giphy-4031660982](https://github.com/user234683/youtube-local/assets/28744867/ba6f8a3c-a986-4739-975c-8de46e55b44e)

Does it happen on latest chromium too?
