### ISSUE TITLE
how server usage?

### ISSUE THREAD

**Issue by arankaren** [user234683/youtube-local#19]
Hello dear developer, how can I configure the application with gunicorn or uwsgi?

**Comment by user234683** [comment]
Some modifications are necessary to do this. In `server.py`, remove the following code at the bottom:
```
if settings.allow_foreign_addresses:
    server = WSGIServer(('0.0.0.0', settings.port_number), site_dispatch,
                        log=FilteredRequestLog())
else:
    server = WSGIServer(('127.0.0.1', settings.port_number), site_dispatch,
                        log=FilteredRequestLog())
print('Started httpserver on port ' , settings.port_number)
server.serve_forever()
```

Then, the callable is named `site_dispatch`. So for instance, in [uwsgi](https://uwsgi-docs.readthedocs.io/en/latest/WSGIquickstart.html), you would use `--callable site_dispatch`. In [gunicorn](https://gunicorn.org/), you would have `server:site_dispatch`, based on what I see for the docs.

I'll add an `if __main__` block shortly for the next release so that modifying server.py will not be necessary.

In general, youtube-local isn't intended to serve more than 1 person or be used as a public instance, if that's what you're looking to do. Something like Invidious is recommended for that use case.

**Comment by arankaren** [comment]
OK thanks friend. I only plan to use it for my home in a local environment. Thank you very much again!!!
