### ISSUE TITLE
Automatically change Tor circuit when the current IP is blocked

### ISSUE THREAD

**Issue by pExeen** [user234683/youtube-local#20]
Oh and thanks for implementing watching videos through Tor, this has replaced Invidious for me now.

**Comment by zrose584** [comment]
I haven't looked at the code (too much), but this should be possible by using stem and wrapping the `fetch_url()` method.
Is this being worked on?

**Comment by user234683** [comment]
I haven't started on it. Stem has a function to get a new identity I believe, so this should be easier than #16. However, it's not completely trivial because of parallel requests. If A and B are going out at the same time, A finishes first with the error, declares new identity (hopefully doesn't break B), B finishes with error, declares new identity again. If the complexity of fixing that is too large, I suppose it's not that bad to just let that happen since it's only occasional. Another potential complication is whether this will interfere with Tor Browser, and whether it will close and reopen.

**Comment by user234683** [comment]
Current release will now try to change the Tor circuit once. Retrying three times is more complicated so will be finished later once I get more time.

**Comment by pExeen** [comment]
Hey thanks for implementing this cool feature. I get the error `stem.connection.MissingPassword: no passphrase provided` when I try to use this though. The password I use is empty.
Right now I use this command to change the circuit:
`echo -e 'authenticate ""\nsignal newnym\nquit' | nc localhost 9051`

**Comment by pExeen** [comment]
You could just fix this my replacing controller.authenticate() with controller.authenticate('')
 on line 115.
