### ISSUE TITLE
Plyr deprecated soon?

### ISSUE THREAD

**Issue by stl3** [user234683/youtube-local#200]
Will there be any plans to move to vidstack from plyr since it will no longer be updated?
https://github.com/sampotts/plyr/issues/2737
I also see that it can cast to Chromecast which is useful (plyr can probably do that too but I've never tried looking into it).

**Comment by user234683** [comment]
There aren't any plans to update plyr since it works good enough as-is. Unless browsers start breaking it or there's some kind of security risk with it (which I doubt since it's mostly just UI), I don't see any reason to update it (we've just been using the 2021 version of plyr without updating it). I chose plyr because it was the leanest option I could find (<10k LoC) and didn't require any frameworks, and vidstack looks like it wants to go to the moon, which isn't really what youtube-local is about.

**Comment by stl3** [comment]
Good points. I myself prefer the leaner route so long as it's functional. I guess so long as it's still working it's not a problem.
