### ISSUE TITLE
Change font

### ISSUE THREAD

**Issue by iFUCKINGHATEcomputers** [user234683/youtube-local#33]
That serif font looks hideous for this purpose. What's an easy way to change it?

Alternatively, just officially change the program to use a sans-serif font, it will look much better,

**Comment by zrose584** [comment]
it can be changed in [shared.css](https://github.com/user234683/youtube-local/blob/e3c311e10a54ae1b7d9114cc58de315157538e0f/youtube/static/shared.css#L15)

**Comment by user234683** [comment]
I remember trying to fix the fonts after finding out they looked broken on Linux, thinking I had found something that worked on Windows as well (I could have sworn I tested it!). I don't know what happened, but yeah something went wrong and it looks awful. I'm going to try fixing it again this week and test it better. The font priority list is such a pain because they all have different sizes. Any font gurus would like to comment on the ideal priority order/best fonts to use?

**Comment by iFUCKINGHATEcomputers** [comment]
> 
> 
> I remember trying to fix the fonts after finding out they looked broken on Linux, thinking I had found something that worked on Windows as well (I could have sworn I tested it!). I don't know what happened, but yeah something went wrong and it looks awful. I'm going to try fixing it again this week and test it better. The font priority list is such a pain because they all have different sizes. Any font gurus would like to comment on the ideal priority order/best fonts to use?

**Comment by iFUCKINGHATEcomputers** [comment]
@zrose584 Thanks.

@user234683 Changing the font to Arial in[ shared.css](https://github.com/user234683/youtube-local/blob/e3c311e10a54ae1b7d9114cc58de315157538e0f/youtube/static/shared.css#L15) worked for me. Maybe change `"liberation serif", "times new roman"` to `"some libre sans serif font", arial`?

**Comment by iFUCKINGHATEcomputers** [comment]
test

**Comment by user234683** [comment]
Nevermind, the problem was just that one of my windows installations had anti-aliasing off for some reason. But I understand aesthetic preferences differ (I personally prefer serif fonts because not being able to distinguish I and l is annoying), so I'll add a setting to choose between some serif and non-serif fonts.
