### ISSUE TITLE
about 'Open in new tab'

### ISSUE THREAD

**Issue by zrose584** [user234683/youtube-local#35]
I think that it's redundant, as you can already use middleclick on the "n replies" summary-element.
https://github.com/user234683/youtube-local/commit/95f2f027eabdcc4dc3c1a77829bf2bf503ed2939

**Comment by user234683** [comment]
Middle click has low discoverability. I put this there for now because sometimes the request fails or times out/takes too long and need to restart Tor. Also nice as a fallback if js is disabled (setting requires extra exploration to find). Maybe I'll remove it if a retry button is implemented or something.
