### ISSUE TITLE
Make site accessible to local network

### ISSUE THREAD

**Issue by megascrapper** [user234683/youtube-local#55]
Is it possible to make youtube-local accessible to the local network?

**Comment by user234683** [comment]
If you go to the settings.txt file there is a hidden setting called `allow_foreign_addresses` which you can enable. Some things to note:
- It will allow any foreign addresses, local or not. So make sure your ports are *not* forwarded, and/or that your firewall blocks non-local requests
- POST requests such as adding videos to playlists are still disabled from foreign addresses. You can find the [code](https://github.com/user234683/youtube-local/blob/master/server.py#L209) for this in `server.py` and remove it.
- It's not officially supported or tested so that's why the setting is hidden. However, I can see the utility of local network access so I may make some settings to only allow the local network
