### ISSUE TITLE
Any way to run this on 32 bit Windows?

### ISSUE THREAD

**Issue by casper** [user234683/youtube-local#6]
The new Youtube layout is slow as snails on older computers. This looks like a really nice alternative, so wondering if there is any way to make this run on 32 bit Windows? Or maybe I could compile it myself?

**Comment by user234683** [comment]
Yes, the windows release is 32 bit, so it should work. If not, let me know what goes wrong

**Comment by user234683** [comment]
Yes, the windows release is 32 bit, so it should work. If not, let me know what goes wrong

**Comment by user234683** [comment]
Yes, the windows release is 32 bit, so it should work. If not, let me know what goes wrong

**Comment by user234683** [comment]
Yes, the windows release is 32 bit, so it should work. If not, let me know what goes wrong

**Comment by user234683** [comment]
Yes, the windows release is 32 bit, so it should work. If not, let me know what goes wrong

**Comment by user234683** [comment]
Yes, the windows release is 32 bit, so it should work. If not, let me know what goes wrong

**Comment by casper** [comment]
Thanks. The problem seems to be it needs Windows 7 minimum. I was trying it on Vista (32-bit) where the Python executable refuses to run. Not sure if this can be fixed, but as of now you can't run it on < Win7.

https://i.imgur.com/xQxHROa.png

**Comment by user234683** [comment]
Odd. The [release page](https://www.python.org/downloads/windows/) for Python 3 says that Windows XP and earlier won't work, so I would expect Vista to work. It's possible that the Visual C++ DLLs I'm including aren't compatible for some reason, or that one of the imports is at fault. I'll try to get a Vista virtual machine running. In the meantime, to debug what's wrong, try opening cmd.exe, `cd` to the youtube-local\python directory, and then run `python.exe`. It should put you into an interactive prompt if it's only the imports that are broken. (If you're not sure how to navigate the command line, double clicking python.exe in that directory should work - if there's no error, it should open a command prompt and immediately close, otherwise it should show the error.)

Now, as for getting it working right now, you can download the [windows python 3 installer](https://www.python.org/downloads/windows/) yourself and install it (make sure you check the box to install PIP during the installation process). Then, you can download the .zip source code release of youtube-local and unzip it. Then, in cmd, cd into that directory and run `pip3 install -r requirements.txt`. Then you can run it using `python3 server.py`.

**Comment by casper** [comment]
Thanks for taking a look at this. If you get it confirmed on a VM it would be great. I tried it in the command prompt like you said, and got the same error.

Next I did a test and copied `python.exe` out of the `python` folder and renamed it `python_test.ext` to make sure I had an unique name. I ran that, and it complained about missing `python38.dll`. I then copied `python38.dll` from the `python` folder and put it next to the `python_test.exe`. Ran it and got the original `GetActiveProcessorCount` error again. So the issue *seems* to be in `python.exe` and/or `python38.dll`.

I will check out installing python separately. Have to think about it a bit, as I have Python 2.7 installed also for another app. Hmm. Will have to see if both can somehow coexist.

**Comment by user234683** [comment]
You can install multiple python versions. Just make sure you uncheck the option to add python to PATH during installation, so that you do not override the `python` command pointing to your 2.7 installation. Then you [add the new installation to the PATH](https://www.computerhope.com/issues/ch000549.htm) by putting the directory containing python.exe at the *end* of the list (so it will have the *least* priority). Then you can use the python3 command to use the new installation, and the old python command will still point to your old installation. Alternatively, you can just type the full path to the new installation when running youtube-local: `"C:\Python38\python.exe" server.py` for example.

**Comment by user234683** [comment]
Python 3.7 appears to work on Windows Vista. I've changed the windows releases to use that version since it will continue receive security patches until 2023. For some reason, brotli had an ImportError on Vista so I modified some things so it won't matter if it fails, since brotli is non-essential anyways. The current release should work on Vista.

**Comment by casper** [comment]
Oh yeah 👍 Worked on the first try. Thanks for the fix. Lightning fast compared to YT.
