### ISSUE TITLE
Migration issue

### ISSUE THREAD

**Issue by prinixos** [user234683/youtube-local#63]
I want to import all my subscription list from **[YouTube](https://www.youtube.com)** or **[Newpipe](https://github.com/TeamNewPipe/NewPipe)** but there is no easy way to do that I have to manually subscribe to the individual channel. Please Help

**Comment by user234683** [comment]
Did you try the import subscriptions feature in the subscriptions manager? You first have to go to Youtube's subscriptions manager while logged in and export the subscriptions at the bottom. I'm going to write some documentation for these things since I acknowledge there's no obvious way to figure it out

**Comment by user234683** [comment]
I added instructions to the readme
