### ISSUE TITLE
Add option to proxy the video through Tor

### ISSUE THREAD

**Issue by pExeen** [user234683/youtube-local#7]
If this feature is added this project would completely replace invidious for me.

**Comment by user234683** [comment]
I'm extremely reluctant to do this because a lot of people streaming video through Tor could put strain on the network. For instance, the Tor project has [warnings](https://blog.torproject.org/bittorrent-over-tor-isnt-good-idea) against torrenting over Tor:
> The first answer is "don't run Bittorrent over Tor". We've been saying for years not to run Bittorrent over Tor, because the Tor network can't handle the load

They even have a [2012 research paper](https://www.robgjansen.com/publications/throttling-sec2012.pdf) trying to figure out mechanisms for how "bandwidth parasites" could be throttled:

> Tor is vulnerable to network congestion and performance problems due to bulk data transfers. A large fraction of the available network capacity is consumed by a small percentage of Tor users, resulting in severe service degradation for the majority. Bulk users continuously drain relays of excess bandwidth, creating new network bottlenecks and exacerbating the effects of existing ones.

So I tend to think this would also apply for streaming a lot of video, since Tor isn't built with that usage in mind. Maybe this situation has changed as of 2020, and streaming video won't be a big deal. I'm open to doing it, but I would want to consult with the Tor project first, since I don't want to do anything that would harm the network, especially as youtube-local gains more users. I'll look into it.

This situation is actually the same as most Invidious instances. Most invidious instances don't route the video traffic, since it's too expensive. I don't recall whether the main Invidious instance did this; I think it did in limited circumstances. I don't currently believe that Google does tracking through the googlevideo requests (I've never seen recommendations on stock Youtube based on what I've watched through youtube-local), though I haven't done a controlled experiment on this yet.

For now, the suggested usage for ensuring anonymity with the video files is to use a VPN instead of Tor. Since the requests to Youtube use https, the VPN operator can't see what is being watched, only that you're accessing youtube.com. Similarly, Youtube would only see traffic coming out of the VPN.

If Google is found to be performing tracking through googlevideo requests, a highly speculative future option would be forming a mixnet for youtube-local through i2p (which unlike Tor, is designed for torrenting and large downloads), where people can seed videos for eachother, similar to Peertube. Though this would be a _lot_ of engineering work that's likely outside of my capability.

**Comment by user938120** [comment]
It looks like the stance that streaming is too stressful for the Tor network is [no longer accurate](https://www.whonix.org/wiki/Tor_Myths_and_Misconceptions#Common_Tor_Myths_and_Misconceptions). While [this](https://trac.torproject.org/projects/tor/wiki/doc/TorifyHOWTO/Misc) official document states torrenting is still too stressful and not recommended, it then proceeds to gives detailed advice on using youtube-dl over tor.

It's unlikely that you can stream anything over 720p well, so putting a limit or recommending the user to lower their preferred resolution if putting the video through Tor would be a good idea. At the very least, I would like to use a setting that disables any connection that's not put through Tor so that the program could be used to browse Youtube without the need for a VPN, even if you can't watch videos.

**Comment by user234683** [comment]
In addition to user938120's findings, I've consulted with some Tor developers, and it looks like it will be fine to go through with this. They recommended including links and a suggestion for donating to the consortium of exit node operators. I'll probably make 360p routed through Tor by default. As for 720p, I'll gather a sample of videos and calculate the average bandwidth for 360p vs 720p and make a decision on handling that. I'll try to get this done this week or next.
