### ISSUE TITLE
plyr and shortcuts

### ISSUE THREAD

**Issue by zrose584** [user234683/youtube-local#71]
I just noticed some shortcuts don't work anymore after 1e65153caa60ea57b1a46227cd672bea2f775171.

So I looked at it and saw hotkeys.js is disabled in favor of plyr builtin(?) shortcuts.
Why is that? Why not always rely on hotkeys.js, and disable plyr's shortcuts?

In case that's not possible one could expose `settings.video_player` as js variable, which is read in hotkeys.js and disables some (but not all!) hotkeys.

**Comment by user234683** [comment]
Good point, I guess I was thinking that the hotkeys plyr is missing would be added additionally, but always using hotkeys.js makes more sense.

**Comment by user234683** [comment]
One issue I'm noticing with hoykeys.js+plyr is that the `c` hotkey enables the browser captions rather than plyr's captions. So if plyr captions are on then you'll get two duplicated captions. And the transcript won't change the video captions or will be out of sync if a different language is selected
