### ISSUE TITLE
Settings & Subs not transferred to new installation

### ISSUE THREAD

**Issue by SlidingHorn** [user234683/youtube-local#77]
I just switched my desktop over to Arch, and installed `youtube-local`. Before making the distro change, I made sure to backup `~/.youtube-local/settings.txt` and `~/.youtube-local/data/subscriptions.sqlite` files so that I could just essentially "plug-and-play".

Unfortunately, when I load ytl, my subscriptions are not seen, nor are my settings (e.g. tor isn't enabled for searching)

Is there an import step I'm missing?  I would really like to avoid having to go through and find *all* of my old subs and manually re-add them if at all possible.

Thanks in advance!

**Comment by user234683** [comment]
Yes, if the files are there it should work. Try the following:
- Check that the console says it is running in *non-portable* mode.
- Check that the working directory is the installation directory (it will enter portable mode if it finds a `settings.txt` file in the working directory and store the data there).
- Double check that the directory `~/.youtube-local/...` is indeed there and doesn't have any typos.
- Check that the `.youtube-local` directory and files have the correct permissions (though I doubt this is the problem since it would give an exception in the console)
- Try running `python3 -i` to enter interactive mode, and then run
`import os; print(os.path.expanduser(os.path.normpath("~")))` to make sure that this gives the correct home directory `/home/[username]`

**Comment by SlidingHorn** [comment]
Hi @user234683 - Thanks for taking a look at my problem :)

> Check that the console says it is running in *non-portable* mode
Check.

```
Running in non-portable mode
Tor routing is OFF - your Youtube activity is NOT anonymous
Started httpserver on port 8080
```
 
>     * Check that the working directory is the installation directory (it will enter portable mode if it finds a `settings.txt` file in the working directory and store the data there).
Check. Not in the directory

>     * Double check that the directory `~/.youtube-local/...` is indeed there and doesn't have any typos.
Check - copied from an `ls -a` in `~`: `.youtube-local`, and the files were pushed to a git repository from the old system and pulled by the new one (i.e. there should be no difference in the file names)

>     * Check that the `~/.youtube-local` directory and files have the correct permissions (though I doubt this is the problem since it would give an exception in the console)
```
ll **
-rw-r--r-- 1 user user 1647 Aug  8 02:01 settings.txt

data:
total 32
-rw-r--r-- 1 user user 32768 Aug  8 00:27 subscriptions.sqlite
```

`data/` itself is `drwxr-xr-x`
>     * Try running `python3 -i` to enter interactive mode, and then run
>       `import os; print(os.path.expanduser(os.path.normpath("~")))` to make sure that this gives the correct home directory `/home/[username]`
`/home/user` is returned.

**Comment by user234683** [comment]
That's a tough one. Maybe the actual files there are blanks/defaults.
- Open settings.txt and see if it has Tor routing enabled. If it's disabled, then the git pull probably didn't work and it has default settings in there.
- To check if the subscriptions.sqlite is blank, go to `~/.youtube-local/data/`, enter interactive mode `python3 -i`, and then execute `import sqlite3; connection = sqlite3.connect('./subscriptions.sqlite'); print('\n'.join(map(str,connection.execute('''SELECT channel_name FROM subscribed_channels''')))); connection.close()`
It should give you the list of subscribed channels. If it doesn't, then the reason no subscriptions are displayed is because the file is blank.

**Comment by SlidingHorn** [comment]
not sure how it's blank, but it is..... 

Well, that sucks, lol
