### ISSUE TITLE
Routes similar to YouTube

### ISSUE THREAD

**Issue by arankaren** [user234683/youtube-local#90]
Hello @user234683 

I've long wondered why the URL is like this?

```
http://localhost:8080/https://www.youtube.com/watch?v=f085KDOy43k
```

Why can't it be used?

```
http://localhost:8080/watch?v=f085KDOy43k
```

or

```
http://localhost:8080/y/watch?v=f085KDOy43k
```

Greetings! :smile:

**Comment by user234683** [comment]
A few reasons:
- It is planned to add support for sites other than YouTube. Doing it this way is easier coding wise (compare to similar clients such as invidious and yotter where they have to do a lot of dancing adding &host=.... to the end of the URL, which results in a lot of bugs and complexity. Additionally, it will ensure there are no conflicts if two services use the same route
- YouTube itself doesn't use a single domain. There are other domains such as youtu.be, ytimg, etc. It makes it easier to write URL redirection rules to just put the domain in front
- It makes it easier to copy the YouTube URL from the URL bar to share with other people, rather than having to copy the /watch part and manually add https://www.youtube.com in front of it

**Comment by arankaren** [comment]
@user234683 thanks for the explanation
